---
- name: Import Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
    state: present

- name: Install Visual Studio Code
  become: true
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
    cache_valid_time: 3600
