# ===== #
# Neovim #
# ===== #
- name: Download Neovim tar.gz
  ansible.builtin.get_url:
    url: "{{ neovim_url }}"
    dest: "/tmp/nvim-linux64.tar.gz"
    mode: "0644"

- name: Extract Neovim tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "{{ neovim_release_dest }}"
    remote_src: true
    creates: "{{ neovim_release_dest }}/nvim-linux64/bin/nvim"

- name: Verify Neovim Installation
  ansible.builtin.command: "{{ neovim_release_dest }}/nvim-linux64/bin/nvim --version"
  register: neovim_version
  changed_when: false

- name: Show Neovim Version
  ansible.builtin.debug:
    msg: "Neovim version installed: {{ neovim_version.stdout_lines[0] }}"

- name: Link Neovim
  ansible.builtin.file:
    src: "{{ neovim_release_dest }}/nvim-linux64/bin/nvim"
    dest: "{{ neovim_bin_link_dest }}"
    state: link
