---
# Source: https://waylonwalker.com/install-rust/
- name: Check if cargo is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_stat

- name: Download Installer
  when: not cargo_stat.stat.exists
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install rust
  when: not cargo_stat.stat.exists
  # when: cargo_exists is failed
  ansible.builtin.command:
    cmd: /tmp/sh.rustup.rs -y
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: out

- name: Print install output
  when: not cargo_stat.stat.exists
  ansible.builtin.debug:
    msg: "{{ out.stdout_lines }}"
