---
# Inspired from: https://github.com/LorenzoBettini/ansible-molecule-oh-my-zsh-example/blob/master/files/zshrc-starship

# ===== #
# Utils #
# ===== #
- name: Install packages with apt
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - git
      - tmux
      - tree
      - htop
      - zsh
      - fzf
    state: present
    update_cache: true
    cache_valid_time: 3600


# === #
# ZSH #
# === #
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Change the default shell to Zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: true

# ======== #
# Starship #
# ======== #
- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  register: starship_installation_script

- name: Install starship with installation script
  become: true
  when: starship_installation_script.changed
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

# ================ #
# TODO: move to chezmoi #
# ================ #
- name: Import .zshrc from files
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
    mode: "0644"

- name: Import starship TOML config
  ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
    mode: "0644"


# ============ #
# Install font #
# ============ #
- name: Create fonts directory
  ansible.builtin.file:
    path: "~/.fonts"
    mode: "0775"
    state: directory

- name: Download Hack
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "~/.fonts/"
    remote_src: true
    creates: "~/.fonts/Hack Bold Italic Nerd Font Complete.ttf"

# ==================== #
# Gnome-terminal theme #
# ==================== #
# TODO: replace with saved dconf file
- name: Create .local/src directory
  ansible.builtin.file:
    path: "~/.local/src/"
    mode: "0775"
    state: directory

- name: Install Gogh
  ansible.builtin.git:
    repo: https://github.com/Gogh-Co/Gogh.git
    version: "v248"
    dest: ~/.local/src/gogh

- name: Apply Gogh theme
  ansible.builtin.shell:
    cmd: ~/.local/src/gogh/installs/aci.sh
    executable: /bin/sh
  environment:
    TERMINAL: gnome-terminal
