---
# Inspired from: https://github.com/LorenzoBettini/ansible-molecule-oh-my-zsh-example/blob/master/files/zshrc-starship

# ===== #
# Utils #
# ===== #
- name: Install packages with apt
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - fzf
      - git
      - htop
      - tmux
      - tree
      - zsh
    state: present
    update_cache: true
    cache_valid_time: 3600


# === #
# ZSH #
# === #
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1

- name: Change the default shell to Zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: true

# ======== #
# Starship #
# ======== #
- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  register: starship_installation_script

- name: Install starship with installation script
  become: true
  when: starship_installation_script.changed
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

# ============ #
# Install font #
# ============ #
- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.fonts"
    mode: "0775"
    state: directory

- name: Download Hack
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ ansible_env.HOME }}/.fonts/"
    remote_src: true
    creates: "{{ ansible_env.HOME }}/.fonts/Hack Bold Italic Nerd Font Complete.ttf"

# ==================== #
# Gnome-terminal theme #
# ==================== #
# TODO: replace with saved dconf file
- name: Create .local/src directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/src/"
    mode: "0775"
    state: directory

- name: Install Gogh
  ansible.builtin.git:
    repo: https://github.com/Gogh-Co/Gogh.git
    version: "v248"
    dest: "{{ ansible_env.HOME }}/.local/src/gogh"

- name: Apply Gogh theme
  ansible.builtin.shell:
    cmd: "{{ ansible_env.HOME }}/.local/src/gogh/installs/aci.sh"
    executable: /bin/sh
  environment:
    TERMINAL: gnome-terminal
