---
- name: Install chezmoi
  community.general.homebrew:
    name:
      - chezmoi

- name: Init chezmoi
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ dotfiles_repo }} --branch {{ dotfiles_branch }}
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"

- name: Update chezmoi
  ansible.builtin.command: chezmoi update --force
  register: chezmoi_update
  changed_when: '"Updating" in chezmoi_update.stderr'
