---
- name: Install Chezmoi from Github .deb
  ansible.builtin.apt:
    deb: "{{ dotfiles_chezmoi_url }}"
  become: true
  become_method: ansible.builtin.sudo

- name: Verify Chezmoi Installation
  ansible.builtin.command:
    cmd: chezmoi --version
  register: chezmoi_version_output
  changed_when: false

- name: Show Chezmoi Version
  ansible.builtin.debug:
    msg: "Chezmoi installed version: {{ chezmoi_version_output.stdout_lines }}"

- name: Init chezmoi
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ dotfiles_repo }} --branch {{ dotfiles_branch }}
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"

# - name: Update chezmoi
#   ansible.builtin.command: chezmoi update --force
#   register: chezmoi_update
#   changed_when: '"Updating" in chezmoi_update.stderr'
